### ISSUE TITLE
Changes to Admin Sign up page

### ISSUE THREAD

**Issue by amitpujar** [oceanbuilders/smartpod#110]
General changes needed to the sign up form:

1. Do not allow special characters in username (@, for example). User will realize this only at the time of submit. I had used my email ID by mistake. Had to go back and enter all the details again.
2. Check if the username exists in the database - *DONE*
3. Check if the email ID exists in the database 
4. Remove SeaPod Name from the sign up form. The admin is associated with the zone. Admins do not have to be associated with any single  SeaPod.
5. Add Back button on the Address page, Phone page and Submit page.
6. Move "Passwords don't match" and other errors text to above the sign up button. 
7. Misalignment of input boxes after you enter 2 different passwords  and hit the submit button. Phone number, SeaPod Zone and Password strength indicator move to the left. SeaPod name (remove this) and password boxes remain center aligned.

**Comment by siddiqss** [comment]
1. Done
2 & 3. There are two ways to sign in a user in Cognito. One way is to use username and other way is to use email address or phone number. In later case, the email address or phone number will be used as username. While creating a userpool, we need to select one method and this can not be changed afterwards. In our case, we have chosen first method i.e. username. In this method, we can sign in user with username and use email as an alias. When we use email as an alias, we can use email as a sign in option but the email should be verified. Now when I check Cognito for a username if it exists or not during Sign up process. It works fine. But Cognito doesn't provide any API to check email. It only checks for verified emails. Email verification is the second process after signing up. When the sign up is complete, user needs to login, verify their email (a verification code will be sent to them via email) and if they don't verify their email (they won't be able to access the admin panel). Now when a user is signing up and they provide an email which is already there in the Cognito DB, if the email is already verified (means that the email is specified for other user) it will send an error that email already exists. And if the email already exists in the Cognito DB but is not verified (means the user who put the email would not be able to access admin panel), there won't be any error and sign up process will be completed (because there is no API to check unverified email). 

It's also done.

4. Done
5. Done
6. Done
7. Done

**Comment by siddiqss** [comment]
Created new user pool for email based login. 
Changed username based sign up and login to email based sign up and log in.
